README.md, test/load_matrix.py, test/load_property_matrix.py, test/load_sif.py
This PR adds README text and example code for loading matrix and pathway data into a arachne database.
=> Matrix load examples

.travis.yml, Makefile
Quick and careless copy of various parts of Funnel's Makefile and TravisCI config.
=> build: Make and TravisCI

conformance/tests/ot_struct.py, protoutil/protoutil.go
This fixes recursive unwrapping of protobuf structures
=> Extracting fix from fold branch to put in as separate PR

README.md, cmd/create/main.go, cmd/drop/main.go, cmd/dump/main.go, cmd/example/main.go, cmd/info/main.go, cmd/list/main.go, cmd/load/main.go, cmd/rdf/main.go, cmd/server/main.go, cmd/stream/main.go, conformance/tests/test_match.py, test/load_matrix.py, test/load_property_matrix.py, test/load_sif.py, test/test_addvertex.py
=> server: change default ports

conformance/tests/ot_index.py, gdbi/pipe_query_engine.go, mongo/mongo_store.go
Also adds conformance test to check for the bug.
=> Fixing bug in the edge index search. 

jsonpath/jsonpath.go, jsonpath/jsonpath_test.go
Adding library function with unit test for method to be used in traversal engine.
=> Checking in initial version of JSONPath comparator

badgerdb/badger_store.go, boltdb/bolt_store.go, kvgraph/interface.go, kvgraph/kvgraph.go
KVGraph was adding vertices and edges one transaction at a time. This speeds things up.
=> Making SetVertex/SetEdge add elements in single transaction

Makefile, aql/python/aql/query.py, config/config.go, conformance/tests/ot_aggregations.py, conformance/tests/ot_basic.py, conformance/tests/ot_fields.py, conformance/tests/ot_mark.py, conformance/tests/ot_where.py, elastic/es_graph.go, engine/core/compile.go, engine/core/processors.go, engine/pipes.go, mongo/compile.go, mongo/mongo_index.go, mongo/mongo_store.go, mongo/percentile.go, mongo/processor.go, mongo/where_evaluator.go
=> Mongo specific compiler

conformance/tests/ot_basic.py, conformance/tests/ot_count.py, mongo/processor.go
=> mongo: fix case where count is 0

docs/docs/databases/elastic/index.html, docs/docs/databases/index.html, docs/docs/databases/kvstore/index.html, docs/docs/databases/mongo/index.html, docs/docs/databases/sql/index.html, docs/docs/developers/index.html, docs/docs/index.html, docs/docs/queries/getting_started/index.html, docs/docs/queries/graphql/index.html, docs/docs/queries/index.html, docs/docs/queries/jsonpath/index.html, docs/docs/queries/operations/index.html, docs/docs/security/basic/index.html, docs/docs/security/index.html, docs/docs/tutorials/amazon/index.html, docs/docs/tutorials/index.html, docs/docs/tutorials/tcga-rna/index.html, docs/download/index.html, docs/index.html, example/load_matrix.py, website/content/docs/tutorials/tcga-rna.md
Adding more methods and options to the load_matrix.py script
=> Additional Matrix loading methods

config/config.go, elastic/graphdb.go, gdbi/interface.go, kvgraph/graphdb.go, mongo/graphdb.go, server/api.go, server/config.go, sql/graphdb.go
Added config option to turn off random sampling to speed up the schema build.
=> added sampling option for schema build process

mongo/compile.go
These changes seem to give us a 15 - 30% speedup on traversals.
=> mongo: faster lookups

Gopkg.lock, conformance/tests/ot_select.py, engine/core/compile.go, engine/core/processors.go, mongo/compile.go, test/processors_test.go
=> Allow for `select` based jump back to previous mark

Dockerfile
Adds Dockerfile that uses two-stage build to create a docker image that is < 50MB.
=> Adding two-stage docker build

Dockerfile, Makefile
Fixes some weirdness around how docker hub was handling builds, listed in #173
=> Docker build fix

docs/docs/index.xml, docs/docs/queries/getting_started/index.html, docs/docs/queries/operations/index.html, docs/index.html, docs/index.xml, gripql/python/README.md, website/content/docs/queries/getting_started.md, website/content/docs/queries/operations.md
=> minor fixes/improvements to docs

conformance/tests/ot_aggregations.py, engine/core/compile.go, mongo/compile.go, mongo/processor.go
Fix aggregation so that it works on edge values as well
=> Aggregate edges

jsengine/v8/v8.go, mongo/graph.go, mongo/graphdb.go, mongo/schema.go, server/api.go, server/server.go
Also adds a timeout for the initial connection to mongo to address #200
=> Ensure Mongo sessions are closed

mongo/compile.go, mongo/compile_test.go
Fix for https://github.com/bmeg/bmeg-etl/issues/333
=> Mongo query size

conformance/tests/ot_distinct.py, mongo/compile.go, mongo/compile_test.go
Fixes distinct method for marked variables in the mongo engine
=> Mongo mark distinct

psql/graphdb.go, psql/util.go, util/postgres.go
port of some useful code from #205
=> add postgres connection utils

docs/index.xml, website/content/docs.md, website/content/download.md, website/content/graph_schemas.md
Updates on text and clarity of  files directly in dir `website/content/`
=> Updates to files in website/content/

cmd/erclient/main.go
Makes server address a positional argument
=> Updating external resource client command line interface

conformance/tests/ot_update.py, grids/graph.go, kvgraph/graph.go
Making sure kvgraph removes all edges attached to a vertex when it is deleted
=> Fixing kvgraph deleteVertex behavior

cmd/schema/main.go, engine/core/processors.go
=> Fixing aggregation error catching

gripql/client.go
Tested with branch feature/gen3-endpoint.
=> adds additional gripql/client functions
