- cmd/root.go
- cmd/stream/main.go
- mongo/convert.go
Adds a Kafka stream reader program that looks for json encoded AQL messages in topics and then pushes them to a arachne server
> Adding kafka stream reading module to arachne

- gdbi/interface.go
- gdbi/pipe_query_engine.go
- mongo/convert.go
- mongo/mongo_store.go
This PR adds wrappers around the pipe invocation to capture timing info. At the end of the query, every phase reports back total time.
> Adding stack timing to query engine

- jsengine/evaluate.go
Examples:
```
arachne list
2017/12/22 19:35:51 Adding goja JS engine
2017/12/22 19:35:51 Adding otto JS engine
bash
test-drive
```
```
arachne
2017/12/22 19:35:50 Adding goja JS engine
2017/12/22 19:35:50 Adding otto JS engine
Usage:
arachne [command]
Available Commands:
bash
create      Create Graph on Arachne Server
drop        Drop Graph on Arachne Server
dump        Dump Data on Arachne Server
```
It's weird to have these debug lines printed for all commands, especially `list`.
> cmd: remove debug lines

- cmd/server/main.go
"arachne" is a better default because it's more recognizable and obvious.
> database: change default database name to arachne

- badgerdb/badger_graph.go
Return values were being shadowed.
> badgerdb: fix GetEdge and GetBundle return vals

- aql/query.go
- aql/util.go
- cmd/dump/main.go
- cmd/info/main.go
- graphql/handler.go
Separates query building from the client. The separation of concerns is easier to understand, and it also allows queries to be created, built, validated, reused, exported, etc. without being tied to a specific client (or even needing to create one).
> aql/go: NewQuery

- Makefile
`go fmt` is really slow compared to `gofmt`
> build: make tidy fast again

- aql/query.go
- aql/util.go
- cmd/dump/main.go
- cmd/info/main.go
- graphql/handler.go
- protoutil/protoutil.go
Adds a few missing methods. Adds a String() method which prints a `V().Has()....etc` style string, great for debugging. Also separates the graph ID from the query, so queries could exist apart from a graph instance.
> aql: improved Query

- kvgraph/keys.go
This fixes an issue where scanning edges would graph edges from in both `test` and `test:schema` graphs. Both have the same prefix (test). The 0 byte on the end makes sure that the graph name is an exact match.
> Adding proper prefix capping

- aql/python/aql/query.py
- conformance/tests/ot_fields.py
- conformance/tests/ot_render.py
- graphserver/server.go
- jsonpath/jsonpath.go
- protoutil/protoutil.go
* Fixes bug that prevented list results from `render`
* When a field that doesn't exist is selected using `fields` or `render` the server will return `Null` in the returned JSON document for that key.
> Aql python bug fixes

- conformance/tests/ot_distinct.py
- engine/core/processors.go
- jsonpath/jsonpath.go
- jsonpath/jsonpath_test.go
- mongo/compile.go
Selected fields must exist for the traveler to be considered part of the unique set.
> Fix `distinct` traversal method behavior

- aql/python/aql/query.py
- aql/python/aql/util.py
Addresses #129 on the client side. The query described in the issue is returned in a similar timeframe using either the python client or curl.
* Sets chunk_size to None in iter_lines method on response object. 
* chunk_size must be of type int or None. A value of None will function differently depending on the value of stream. stream=True will read data as it arrives in whatever size the chunks are received. If stream=False, data is returned as a single chunk. http://docs.python-requests.org/en/master/api/#requests.Response.iter_content
* Add debug logging to execute. See below. `<Query instance>.execute(debug=True)`
```
[DEBUG]    2018-08-01 10:50:13,692    POST http://arachne.compbio.ohsu.edu/v1/graph/bmeg/query
[DEBUG]    2018-08-01 10:50:13,694    BODY {"query": [{"v": []}, {"where": …
```
> aql/python: add some debugging info to queries

- Gopkg.lock
- Gopkg.toml
- cmd/rdf/main.go
- gripql/client.go
- website/content/docs/tutorials/pathway-commons.md
Making sure the RDF converter code outputs with label data.
> RDF output fix

- gripql/python/gripql/query.py
- gripql/python/tests/wrap_value_test.py
This makes it so that the following two queries are equivalent:
```
query.V().where(gripql.eq("_label", "Aliquot")).in_().count()
```
```
query.V().where(gripql.eq("_label", "Aliquot")).in_(None).count()
```
> gripql/python: passing None to in_(), out(), both(), etc. should have no effect

- Gopkg.lock
- engine/core/processors.go
- kvgraph/index.go
- kvgraph/test/index_test.go
- kvindex/kvindex.go
- server/api.go
For GRPC client, if a transport error is encountered, continue to read the traversal channel so search functions don't get locked on send channels.
This should fix #156
> Finish query stream on error

- gripql/python/gripql/query.py
This is a simple but effective (in the cases I have tested) method to allow python 3.5-3.6 compatibility, a la #158.
> Decode results before loading json.

- conformance/tests/ot_fields.py
- conformance/tests/ot_mark.py
- docs/docs/queries/operations/index.html
- engine/core/processors.go
- gdbi/traveler.go
- jsonpath/jsonpath.go
- jsonpath/jsonpath_test.go
- mongo/compile.go
- test/processors_test.go
- website/content/docs/queries/operations.md
Fields method can now only operate on the current traveler, not the marks. Also implemented logic to exclude fields (e.g. `V().Fields("-_data.expression")`
TODO:
> Fields method refinement / bugfix

- cmd/schema/main.go
- gripql/schema/scan.go
- gripql/schema/schema_test.go
> cmd/schema: add exclude labels flag to schema scanner

- cmd/schema/main.go
- gripql/query.go
- gripql/schema/scan.go
Known issues:
- possible to miss some edge from/to combos when edges are polymorphic
- edge schema lookup will fail for edges that reference vertices that don't exist
> cmd/schema/sample: avoid expensive lookups

- mongo/processor.go
Setting option to allow mongo aggregation pipeline to use disk based temp files.
This fixes issue around `distinct` call failing on large datasets
> Mongo - AllowDiskUse

- website/content/docs/queries/iterations.md
This PR adds the ability to create dynamic length graph traversals using GripQL. This is done via a 'mark' and 'jump' based interface, similar to using a 'goto' statement, but for the stream processor. 
While more primitive than the repeat mechanisms seen in Gremlin, this allows for a much more simple query compilation and implementation. 
The PR adds 4 new operations:
- `mark(name)` : Mark a segment in the stream processor, with a `name`, that can receive jumps
- `jump(dest, condition, emit)` : If a condition is true, send traveler to `mark`. If `emit` is true, also send a copy down the processing chain. If condition is `None`, always do jump.
- `set(field, value)` : Set values within the travelers memory. Can be used to store cycle counts
- `increment(field, value)` : Increment field, …
> Feature: Adding jump based repeat pattern to GripQL [WIP]
